Adding types to declaration merge for route transact option in typesc…
fastify/fastify-postgres pull request #142
Opened 2022-08-12 05:02 UTC by bdun94

Extended `FastifyRequest` and `RouteShorthandOptions` so that the transact route option is usable in typescript. Basically added in the missing definitions in the typescript declaration merging so that when using the transact route typescript compile errors are not thrown

resolves #141 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included 
- [ ] documentation is changed or added (don't think it's necessary for this change?)
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-08-12 05:29 UTC, climba03003 requested changes
Can you clean up the unnecessary styles changes?
e.g. quotes

2022-08-16 02:24 UTC, bdun94 commented
sorry about that @climba03003 should've caught that, let me know if there's anything else that needs to be changed

2022-08-16 03:59 UTC, climba03003 approved these changes

2022-08-16 06:34 UTC, Uzlopak commented on index.d.ts
> +  export interface RouteShorthandOptions {
nitpick:

```suggestion

  export interface RouteShorthandOptions {
```

2022-08-16 06:35 UTC, Uzlopak approved these changes
LGTM, just a nitpick

2022-08-16 07:37 UTC, mcollina approved these changes
lgtm

2022-08-16 07:38 UTC, merged